adds new automated tests
trade-tariff/trade-tariff-testing pull request #1184
Opened 2023-06-15 14:35 UTC by bhavanibandla

Jira link

- HOTT-3380
- HOTT-3319
- HOTT-3336

What?
I have added/removed/altered the following:

- Added automated tests for search results changes, title bug fixes, and CDS instructions for NZ/AU.

Why?
I am doing this because:

- To ensure that new and existing functionalities work as expected.

2023-06-16 08:06 UTC, jebw requested changes
LGTM but the footer link selectors are brittle, I appreciate you're only linting those files but it'll make the specs more robust, thanks

2023-06-16 08:06 UTC, jebw commented on cypress/e2e/UK/FE/pageLinks-UK.cy.js
> +    cy.get('div:nth-of-type(2) > .govuk-footer__list > li:nth-of-type(2) > .govuk-footer__link')
If we're changing this can we replace the selector (and all these footer selectors) with

```
cy.get('.govuk-footer-link').should('have.attr
```

Thats enough to ensure you are checking the footer link is there - the rest is just making the test brittle, if we add a footer link prior to the expected one then the spec fails despite the expected footer link still being there.

2023-06-19 10:21 UTC, bhavanibandla commented on cypress/e2e/UK/FE/pageLinks-UK.cy.js
> +    cy.get('div:nth-of-type(2) > .govuk-footer__list > li:nth-of-type(2) > .govuk-footer__link')
updated locators in the pageLinks-UK and pageLinks-XI spec files.

2023-06-19 10:45 UTC, jebw approved these changes

2023-06-19 10:48 UTC, merged