fixes for regression failures
trade-tariff/trade-tariff-testing pull request #952
Opened 2022-11-01 14:24 UTC by bhavanibandla

Jira link

- Fixes for regression failures

What?
I have added/removed/altered the following:

- Executed regression tests on my local machine, went through each regression failure spec file and managed to fix some of the tests.

Why?
I am doing this because:

- Working towards making regression tests 100% green so need to fix all failures.

2022-11-02 10:29 UTC, jebw requested changes

2022-11-02 10:29 UTC, jebw commented on cypress/e2e/Quotas/quotasPopup-UK.cy.js
> +    if (`${future_month}`.includes('0')) {
eg, using `.replace(/^0/, '')` to strip leading zeros only if present

2022-11-03 10:21 UTC, bhavanibandla commented on cypress/e2e/Quotas/quotasPopup-UK.cy.js
> +    if (`${future_month}`.includes('0')) {
Refactored the quota popup spec file as we discussed hence marking this as resolved.

2022-11-03 10:23 UTC, bhavanibandla commented on cypress/e2e/Quotas/quotasPopup-UK.cy.js
> +  const todays_Date = `${todaysDate}`.replace(/^0|[^\/]0./, '');
Removed unnecessary variables and used 'D' instead to avoid using replace '0' with ''

2022-11-03 17:09 UTC, jebw approved these changes
Looks great and much simpler :raised_hands:

2022-11-03 17:09 UTC, jebw commented on cypress/e2e/Quotas/quotasPopup-UK.cy.js
> +  const previousDate = dayjs().subtract(1, 'M').format('D MMM YYYY');
Not a blocker but potential suggestion for the future. This is converting the date object (a machine understandable structured representation of a date) to a string (unstructured) - it is then relying on the dateToUrl helper to parse that string correctly and turn it back into a structured type. 

The format used means that conversion is unambiguous so this will work fine _but_ there are problems around parsing formats like UKs `dd/mm/yyyy` which looks the same to a parser as US's `mm/dd/yyyy` - hence the preference to keeping dates in structured form as late as possible.

If it was instead to remain a Dayjs object - eg, `dayjs().subtract(1, 'M')` - then you could convert it to the desired string format at the point of usage, eg either

```javascript
`/some/path?${helper.dateToUrl(previousDate)`
```

:point_up: then doesn't need to parse the date to decide how to build the URL, or 

```javascript
.contains(`Balance (as of ${previousDate.format('D MMM YYYY')})`)
```

to convert to desired string format

2022-11-03 17:20 UTC, bhavanibandla commented on cypress/e2e/Quotas/quotasPopup-UK.cy.js
> +  const previousDate = dayjs().subtract(1, 'M').format('D MMM YYYY');
Okay, got you :)

2022-11-03 17:20 UTC, merged